const {
  slash,
  backSlash,
  systemSlash,
  shortPath,
  prependProjectPath,
} = require('./path');
const constants = require('./const');

module.exports = {
  findFileOnPath: require('./find-file-on-path'),
  forceLinkXCodeProject: require('./force-link-xcode-project'),
  fetchPublishingProperties: require('./fetch-publishing-properties'),
  getAppDelegateHeaderPath: require('./get-app-delegate-header-path'),
  getAppDelegatePath: require('./get-app-delegate-path'),
  getAppEntitlementsPath: require('./get-app-entitlements-path'),
  getXcodeProjectPath: require('./get-xcode-project-path'),
  getXcodeProjectName: require('./get-xcode-project-name'),
  getAppConfiguration: require('./get-app-configuration'),
  getBuildConfiguration: require('./get-build-configuration'),
  getInfoPlistPath: require('./get-info-plist-path'),
  getPodfilePath: require('./get-podfile-template-path'),
  getPodfileTemplatePath: require('./get-podfile-template-path'),
  getProductionBuildInfo: require('./get-production-build-info'),
  getMainActivityPath: require('./get-main-activity-path'),
  getMainApplicationPath: require('./get-main-application-path'),
  getAppGradlePath: require('./get-app-gradle-path'),
  getGradlePropertiesPath: require('./get-gradle-properties-path'),
  getGradleConstantsPath: require('./get-gradle-constants-path'),
  getSettingsGradlePath: require('./get-settings-gradle-path'),
  getRootGradlePath: require('./get-root-gradle-path'),
  getAndroidManifestPath: require('./get-android-manifest-path'),
  getResStringsPath: require('./get-res-strings-path'),
  isWindows: require('./is-windows'),
  projectPath: require('./get-project-path'),
  reactNativeLink: require('./react-native-link'),
  resetDiff: require('./reset-diff'),
  sanitizeDiff: require('./sanitize-diff'),
  updateAndroidPackageName: require('./update-android-package-name'),
  inject: require('./inject'),
  replace: require('./replace'),
  files: require('./files'),
  slash,
  backSlash,
  systemSlash,
  shortPath,
  prependProjectPath,
  ANCHORS: constants.ANCHORS,
  filesChangedByConfigurationScript:
    constants.filesChangedByConfigurationScript,
};
