const {
  slash,
  backSlash,
  systemSlash,
  shortPath,
  prependProjectPath,
} = require('./path');
const constants = require('./const');

module.exports = {
  findFileOnPath: require('./find-file-on-path'),
  reactNativeLink: require('./react-native-link'),
  forceLinkXCodeProject: require('./force-link-xcode-project'),
  getAppDelegateHeaderPath: require('./get-app-delegate-header-path'),
  getAppDelegatePath: require('./get-app-delegate-path'),
  getXcodeProjectPath: require('./get-xcode-project-path'),
  getXcodeProjectName: require('./get-xcode-project-name'),
  getAppConfiguration: require('./get-app-configuration'),
  getBuildConfiguration: require('./get-build-configuration'),
  getInfoPlistPath: require('./get-info-plist-path'),
  projectPath: require('./get-project-path'),
  isWindows: require('./is-windows'),
  getPodfileTemplatePath: require('./get-podfile-template-path'),
  getMainActivityPath: require('./get-main-activity-path'),
  getMainApplicationPath: require('./get-main-application-path'),
  getAppGradlePath: require('./get-app-gradle-path'),
  getGradlePropertiesPath: require('./get-gradle-properties-path'),
  getSettingsGradlePath: require('./get-settings-gradle-path'),
  getAndroidManifestPath: require('./get-android-manifest-path'),
  inject: require('./inject'),
  replace: require('./replace'),
  files: require('./files'),
  slash,
  backSlash,
  systemSlash,
  shortPath,
  prependProjectPath,
  ANCHORS: constants.ANCHORS,
};
