# Careful when editing the code below with the RN upgrades
# This is a more generic version of the RN code execution that extends
# the default behaviour by allowing to run multiple node scripts

def node_require(script)
  # Resolve script with node to allow for hoisting
  require Pod::Executable.execute_command('node', ['-p',
    "require.resolve(
      '#{script}',
      {paths: [process.argv[1]]},
    )", __dir__]).strip
end

# Resolve react_native_pods.rb with node to allow for hoisting
node_require('react-native/scripts/react_native_pods.rb')

## <Additional node scripts>

platform :ios, min_ios_version_supported
prepare_react_native_project!

## <Post prepare RN project>

install! 'cocoapods', :deterministic_uuids => false

target 'ShoutemApp' do
  $config = use_native_modules!

  use_frameworks! :linkage => :static
  ## <Static frameworks>

  use_react_native!(
    :path => $config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  ## <Extension dependencies>

end

## <Additional target>

post_install do |installer|
  # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
  react_native_post_install(
    installer,
    $config[:reactNativePath],
    :mac_catalyst_enabled => false
  )
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
      config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
      config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
    end

    ## <Extension postinstall targets>
  end
end
